name: Preview Deployment

on:
  push:
    branches: ['release/*']

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install_dependencies
        run: yarn install
      - name: run_typescript_check
        run: 'yarn typecheck'
      - name: run_tests
        run: 'yarn test'

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install_vercel_cli
        run: yarn global add vercel@latest
      - name: pull_vercel_environment_information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: build_project_artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy_project_artifacts_to_vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
